version: 2.1
orbs:
  heroku: circleci/heroku@1.0.0
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/lansingcodes/lubot
    environment:
      TZ: America/Detroit
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-dep-
      - run:
          command: |
            npm install
            npm test
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
workflows:
  test-and-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: firebase
